backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: dgxp6vwij
    api_key: 677255775569822
    multiple: true

collections:
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Mostrar en pagina principal",
          name: "isLanding",
          widget: "boolean",
          default: false,
        }
      - name: imageGallery
        label: ImageGallery
        widget: "image"
        media_library:
          config:
            allow_multiple: true